# Generated by Django 4.2.6 on 2024-03-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleImage',
            new_name='ArticleImages',
        ),
        migrations.AlterModelOptions(
            name='articleimages',
            options={'ordering': ['article'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(default='src/assets/images/zaglushka.jpg', upload_to='', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=1023, verbose_name='Заголовок'),
        ),
    ]
