# Generated by Django 4.2.6 on 2024-03-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_articleimage_articleimages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(default='zaglushka.jpg', upload_to='', verbose_name='Фотография'),
        ),
    ]
