# Generated by Django 4.2.6 on 2024-03-07 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleImages',
            new_name='ArticleImage',
        ),
    ]
