# Generated by Django 4.2.6 on 2024-03-13 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleimage',
            options={'ordering': ['order'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='description',
            new_name='content',
        ),
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='articleimage',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок вывода'),
        ),
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(default='zaglushka.jpg', upload_to='content/news', verbose_name='Фотография'),
        ),
    ]
