# Generated by Django 4.2.6 on 2024-04-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_articleimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='photo',
            field=models.ImageField(blank=True, upload_to='content/news/gallery', verbose_name='Фотография'),
        ),
    ]
