# Generated by Django 4.2.6 on 2024-04-04 08:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_articleimage_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('file_content', models.FileField(blank=True, null=True, upload_to='content/news/documents', validators=[django.core.validators.FileExtensionValidator(('pdf', 'doc', 'docx'))], verbose_name='Документ')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='articles.article', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['id'],
            },
        ),
    ]
