# Generated by Django 4.2.6 on 2024-04-01 06:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memory',
            options={'ordering': ['id'], 'verbose_name': 'Память', 'verbose_name_plural': 'Память'},
        ),
        migrations.AddField(
            model_name='memory',
            name='file_content',
            field=models.FileField(blank=True, upload_to='content/documents', validators=[django.core.validators.FileExtensionValidator(('pdf', 'doc', 'docx'))], verbose_name='Документ'),
        ),
    ]
