# Generated by Django 4.2.6 on 2024-04-03 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_memory_options_memory_file_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='file_content',
            field=models.FileField(blank=True, null=True, upload_to='content/documents', validators=[django.core.validators.FileExtensionValidator(('pdf', 'doc', 'docx'))], verbose_name='Документ'),
        ),
    ]
