# Generated by Django 4.2.6 on 2024-04-03 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_memory_file_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('file_content', models.FileField(blank=True, null=True, upload_to='content/reports', validators=[django.core.validators.FileExtensionValidator(('pdf', 'doc', 'docx'))], verbose_name='Документ')),
                ('presentation_content', models.FileField(blank=True, null=True, upload_to='content/reports', validators=[django.core.validators.FileExtensionValidator(('pdf', 'doc', 'docx', 'pptx'))], verbose_name='Презентация')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
                'ordering': ['id'],
            },
        ),
    ]
